### ISSUE TITLE
Unable to start pyton script - can't open file

### ISSUE THREAD

**Issue by zorion8282** [kiltonred/satoshi-piggy-bank#1]
Hi, tried your script but im stuck at running the script.

I tried to winscp to the mentioned location but there is no .py I found the .py in the /code folder but am unable to start from there.

BTC Addres below is incorrect for privacy purposes

`pi@raspberrypi:~$ sudo python3 ./satoshi-piggy-bank/piggy-bank.py --address 1hBH6kmeJYBzZuCTWdbV5u --fontsize 11 --lineheight 20 --refreshrate 3600
python3: can't open file './satoshi-piggy-bank/piggy-bank.py': [Errno 2] No such file or directory
pi@raspberrypi:~$ sudo python3 ./satoshi-piggy-bank/code/piggy-bank.py --address 1hBH6kmeJYBzUS73mdWdbV5u --fontsize 11 --lineheight 20 --refreshrate 3600
Traceback (most recent call last):
  File "./satoshi-piggy-bank/code/piggy-bank.py", line 4, in <module>
    from board import SCL, SDA
ModuleNotFoundError: No module named 'board'
pi@raspberrypi:~$                              `

**Comment by kas21e6** [comment]
Thanks for reporting the issue.

The problem was that the path to the `piggy-bank.py` file in the instructions was incorrect. I've fixed it. The correct path is `./satoshi-piggy-bank/code/piggy-bank.py`

**Comment by zorion8282** [comment]
Thanks, I found out the location already but am getting different errors now:

Traceback (most recent call last):
  File "./satoshi-piggy-bank/code/piggy-bank.py", line 49, in <module>
    i2c = busio.I2C(SCL, SDA)
NameError: name 'busio' is not defined

**Comment by kas21e6** [comment]
Did you modify the file `piggy-bank.py`? I don't understand why the program would complain about `busio` being not defined when it's imported at line 5 at the top of the file.
